//
// Copyright Antoine Leblanc 2015
// http://nauths.fr
//
// Distributed under the Boost Software License, Version 1.0. (See
// accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)
//

#ifndef BOOST_PREPROCESSOR_ARRAY_SORT_HPP
# define BOOST_PREPROCESSOR_ARRAY_SORT_HPP



# include <boost/preprocessor/array/lower_bound.hpp>
# include <boost/preprocessor/array/insert.hpp>

/*
** BOOST_PP_ARRAY_SORT
** Sorts the given PP_ARRAY.
** _U variants remove duplicates.
** _D variants use the next available PP_WHILE iteration
*/

# define BOOST_PP_ARRAY_SORT(      A) BOOST_PP_CAT(BOOST_PP_AS_S_,     BOOST_PP_ARRAY_SIZE(A))(  A)
# define BOOST_PP_ARRAY_SORT_U(    A) BOOST_PP_CAT(BOOST_PP_AS_S_U_,   BOOST_PP_ARRAY_SIZE(A))(  A)
# define BOOST_PP_ARRAY_SORT_D(  D,A) BOOST_PP_CAT(BOOST_PP_AS_S_D_,   BOOST_PP_ARRAY_SIZE(A))(D,A)
# define BOOST_PP_ARRAY_SORT_U_D(D,A) BOOST_PP_CAT(BOOST_PP_AS_S_U_D_, BOOST_PP_ARRAY_SIZE(A))(D,A)



/*
** Internal helpers
*/

# define BOOST_PP_AS_PBIF_0(A,X) BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_ARRAY_SIZE(A),0), BOOST_PP_ARRAY_PUSH_BACK, BOOST_PP_AS_PBIF_1)(A,X)
# define BOOST_PP_AS_PBIF_1(A,X) BOOST_PP_IIF(BOOST_PP_EQUAL(BOOST_PP_ARRAY_ELEM(BOOST_PP_DEC(BOOST_PP_ARRAY_SIZE(A)),A),X), BOOST_PP_AS_PBIF_2, BOOST_PP_ARRAY_PUSH_BACK)(A,X)
# define BOOST_PP_AS_PBIF_2(A,X) A

# define BOOST_PP_AS_PRED_0(D,S)     BOOST_PP_AS_PRED_1(D, BOOST_PP_TUPLE_ELEM(4,0,S), BOOST_PP_TUPLE_ELEM(4,1,S), BOOST_PP_TUPLE_ELEM(4,2,S))
# define BOOST_PP_AS_PRED_1(D,I,N,A) BOOST_PP_BITAND(BOOST_PP_LESS_D(D,I,N), BOOST_PP_LESS_D(D,I,BOOST_PP_DEC(BOOST_PP_ARRAY_SIZE(A))))

# define BOOST_PP_AS_OP_0(D,S)             BOOST_PP_AS_OP_1(D, BOOST_PP_TUPLE_ELEM(4,1,S), BOOST_PP_TUPLE_ELEM(4,2,S), BOOST_PP_TUPLE_ELEM(4,3,S), BOOST_PP_TUPLE_ELEM(4,0,S))
# define BOOST_PP_AS_OP_1(D,N,A,R,I)       BOOST_PP_AS_OP_2(D,N,A,R,I, BOOST_PP_INC(I))
# define BOOST_PP_AS_OP_2(D,N,A,R,I,J)     BOOST_PP_AS_OP_3(D,N,A,R,I,J, BOOST_PP_ARRAY_ELEM(I,A), BOOST_PP_ARRAY_ELEM(J,A))
# define BOOST_PP_AS_OP_3(D,N,A,R,I,J,X,Y) BOOST_PP_IIF(BOOST_PP_LESS_D(D,X,Y), BOOST_PP_AS_OP_X, BOOST_PP_AS_OP_Y)(D,N,A,R,I,J,X,Y)
# define BOOST_PP_AS_OP_X(D,N,A,R,I,J,X,Y) (BOOST_PP_INC(I), N, BOOST_PP_ARRAY_REMOVE_D(D,A,I), BOOST_PP_ARRAY_INSERT_D(D,R,X))
# define BOOST_PP_AS_OP_Y(D,N,A,R,I,J,X,Y) (BOOST_PP_INC(I), N, BOOST_PP_ARRAY_REMOVE_D(D,A,J), BOOST_PP_ARRAY_INSERT_D(D,R,Y))

# define BOOST_PP_AS_OP_U_0(D,S)             BOOST_PP_AS_OP_U_1(D, BOOST_PP_TUPLE_ELEM(4,1,S), BOOST_PP_TUPLE_ELEM(4,2,S), BOOST_PP_TUPLE_ELEM(4,3,S), BOOST_PP_TUPLE_ELEM(4,0,S))
# define BOOST_PP_AS_OP_U_1(D,N,A,R,I)       BOOST_PP_AS_OP_U_2(D,N,A,R,I, BOOST_PP_INC(I))
# define BOOST_PP_AS_OP_U_2(D,N,A,R,I,J)     BOOST_PP_AS_OP_U_3(D,N,A,R,I,J, BOOST_PP_ARRAY_ELEM(I,A), BOOST_PP_ARRAY_ELEM(J,A))
# define BOOST_PP_AS_OP_U_3(D,N,A,R,I,J,X,Y) BOOST_PP_IIF(BOOST_PP_LESS_D(D,X,Y), BOOST_PP_AS_OP_U_X, BOOST_PP_AS_OP_U_Y)(D,N,A,R,I,J,X,Y)
# define BOOST_PP_AS_OP_U_X(D,N,A,R,I,J,X,Y) (BOOST_PP_INC(I), N, BOOST_PP_ARRAY_REMOVE_D(D,A,I), BOOST_PP_AS_PBIF_0(R,X))
# define BOOST_PP_AS_OP_U_Y(D,N,A,R,I,J,X,Y) (BOOST_PP_INC(I), N, BOOST_PP_ARRAY_REMOVE_D(D,A,J), BOOST_PP_AS_PBIF_0(R,Y))

# define BOOST_PP_AS_STEP(      A,N) BOOST_PP_TUPLE_ELEM(4,3, BOOST_PP_WHILE(                  BOOST_PP_AS_PRED_0, BOOST_PP_AS_OP_0,   (0,N,A,(0,()))))
# define BOOST_PP_AS_STEP_U(    A,N) BOOST_PP_TUPLE_ELEM(4,3, BOOST_PP_WHILE(                  BOOST_PP_AS_PRED_0, BOOST_PP_AS_OP_U_0, (0,N,A,(0,()))))
# define BOOST_PP_AS_STEP_D(  D,A,N) BOOST_PP_TUPLE_ELEM(4,3, BOOST_PP_CAT(BOOST_PP_WHILE_, D)(BOOST_PP_AS_PRED_0, BOOST_PP_AS_OP_0,   (0,N,A,(0,()))))
# define BOOST_PP_AS_STEP_U_D(D,A,N) BOOST_PP_TUPLE_ELEM(4,3, BOOST_PP_CAT(BOOST_PP_WHILE_, D)(BOOST_PP_AS_PRED_0, BOOST_PP_AS_OP_U_0, (0,N,A,(0,()))))

# define BOOST_PP_AS_S_0(      A) A
# define BOOST_PP_AS_S_U_0(    A) A
# define BOOST_PP_AS_S_D_0(  D,A) A
# define BOOST_PP_AS_S_U_D_0(D,A) A

# define BOOST_PP_AS_S_1(      A) A
# define BOOST_PP_AS_S_U_1(    A) A
# define BOOST_PP_AS_S_D_1(  D,A) A
# define BOOST_PP_AS_S_U_D_1(D,A) A

# define BOOST_PP_AS_S_2(      A) BOOST_PP_AS_STEP(      A,1)
# define BOOST_PP_AS_S_U_2(    A) BOOST_PP_AS_STEP_U(    A,1)
# define BOOST_PP_AS_S_D_2(  D,A) BOOST_PP_AS_STEP_D(  D,A,1)
# define BOOST_PP_AS_S_U_D_2(D,A) BOOST_PP_AS_STEP_U_D(D,A,1)

# define BOOST_PP_AS_S_3(      A) BOOST_PP_AS_S_2(       BOOST_PP_AS_STEP(      A,2))
# define BOOST_PP_AS_S_U_3(    A) BOOST_PP_AS_S_U_2(     BOOST_PP_AS_STEP_U(    A,2))
# define BOOST_PP_AS_S_D_3(  D,A) BOOST_PP_AS_S_U_2(  D, BOOST_PP_AS_STEP_D(  D,A,2))
# define BOOST_PP_AS_S_U_D_3(D,A) BOOST_PP_AS_S_U_D_2(D, BOOST_PP_AS_STEP_U_D(D,A,2))

# define BOOST_PP_AS_S_3(      A) BOOST_PP_AS_S_2(       BOOST_PP_AS_STEP(      A,2))
# define BOOST_PP_AS_S_U_3(    A) BOOST_PP_AS_S_U_2(     BOOST_PP_AS_STEP_U(    A,2))
# define BOOST_PP_AS_S_D_3(  D,A) BOOST_PP_AS_S_U_2(  D, BOOST_PP_AS_STEP_D(  D,A,2))
# define BOOST_PP_AS_S_U_D_3(D,A) BOOST_PP_AS_S_U_D_2(D, BOOST_PP_AS_STEP_U_D(D,A,2))

# define BOOST_PP_AS_S_4(      A) BOOST_PP_AS_S_3(       BOOST_PP_AS_STEP(      A,3))
# define BOOST_PP_AS_S_U_4(    A) BOOST_PP_AS_S_U_3(     BOOST_PP_AS_STEP_U(    A,3))
# define BOOST_PP_AS_S_D_4(  D,A) BOOST_PP_AS_S_U_3(  D, BOOST_PP_AS_STEP_D(  D,A,3))
# define BOOST_PP_AS_S_U_D_4(D,A) BOOST_PP_AS_S_U_D_3(D, BOOST_PP_AS_STEP_U_D(D,A,3))

# define BOOST_PP_AS_S_5(      A) BOOST_PP_AS_S_4(       BOOST_PP_AS_STEP(      A,4))
# define BOOST_PP_AS_S_U_5(    A) BOOST_PP_AS_S_U_4(     BOOST_PP_AS_STEP_U(    A,4))
# define BOOST_PP_AS_S_D_5(  D,A) BOOST_PP_AS_S_U_4(  D, BOOST_PP_AS_STEP_D(  D,A,4))
# define BOOST_PP_AS_S_U_D_5(D,A) BOOST_PP_AS_S_U_D_4(D, BOOST_PP_AS_STEP_U_D(D,A,4))

# define BOOST_PP_AS_S_6(      A) BOOST_PP_AS_S_5(       BOOST_PP_AS_STEP(      A,5))
# define BOOST_PP_AS_S_U_6(    A) BOOST_PP_AS_S_U_5(     BOOST_PP_AS_STEP_U(    A,5))
# define BOOST_PP_AS_S_D_6(  D,A) BOOST_PP_AS_S_U_5(  D, BOOST_PP_AS_STEP_D(  D,A,5))
# define BOOST_PP_AS_S_U_D_6(D,A) BOOST_PP_AS_S_U_D_5(D, BOOST_PP_AS_STEP_U_D(D,A,5))

# define BOOST_PP_AS_S_7(      A) BOOST_PP_AS_S_6(       BOOST_PP_AS_STEP(      A,6))
# define BOOST_PP_AS_S_U_7(    A) BOOST_PP_AS_S_U_6(     BOOST_PP_AS_STEP_U(    A,6))
# define BOOST_PP_AS_S_D_7(  D,A) BOOST_PP_AS_S_U_6(  D, BOOST_PP_AS_STEP_D(  D,A,6))
# define BOOST_PP_AS_S_U_D_7(D,A) BOOST_PP_AS_S_U_D_6(D, BOOST_PP_AS_STEP_U_D(D,A,6))

# define BOOST_PP_AS_S_8(      A) BOOST_PP_AS_S_7(       BOOST_PP_AS_STEP(      A,7))
# define BOOST_PP_AS_S_U_8(    A) BOOST_PP_AS_S_U_7(     BOOST_PP_AS_STEP_U(    A,7))
# define BOOST_PP_AS_S_D_8(  D,A) BOOST_PP_AS_S_U_7(  D, BOOST_PP_AS_STEP_D(  D,A,7))
# define BOOST_PP_AS_S_U_D_8(D,A) BOOST_PP_AS_S_U_D_7(D, BOOST_PP_AS_STEP_U_D(D,A,7))

# define BOOST_PP_AS_S_9(      A) BOOST_PP_AS_S_8(       BOOST_PP_AS_STEP(      A,8))
# define BOOST_PP_AS_S_U_9(    A) BOOST_PP_AS_S_U_8(     BOOST_PP_AS_STEP_U(    A,8))
# define BOOST_PP_AS_S_D_9(  D,A) BOOST_PP_AS_S_U_8(  D, BOOST_PP_AS_STEP_D(  D,A,8))
# define BOOST_PP_AS_S_U_D_9(D,A) BOOST_PP_AS_S_U_D_8(D, BOOST_PP_AS_STEP_U_D(D,A,8))

# define BOOST_PP_AS_S_10(      A) BOOST_PP_AS_S_9(       BOOST_PP_AS_STEP(      A,9))
# define BOOST_PP_AS_S_U_10(    A) BOOST_PP_AS_S_U_9(     BOOST_PP_AS_STEP_U(    A,9))
# define BOOST_PP_AS_S_D_10(  D,A) BOOST_PP_AS_S_U_9(  D, BOOST_PP_AS_STEP_D(  D,A,9))
# define BOOST_PP_AS_S_U_D_10(D,A) BOOST_PP_AS_S_U_D_9(D, BOOST_PP_AS_STEP_U_D(D,A,9))

# define BOOST_PP_AS_S_11(      A) BOOST_PP_AS_S_10(       BOOST_PP_AS_STEP(      A,10))
# define BOOST_PP_AS_S_U_11(    A) BOOST_PP_AS_S_U_10(     BOOST_PP_AS_STEP_U(    A,10))
# define BOOST_PP_AS_S_D_11(  D,A) BOOST_PP_AS_S_U_10(  D, BOOST_PP_AS_STEP_D(  D,A,10))
# define BOOST_PP_AS_S_U_D_11(D,A) BOOST_PP_AS_S_U_D_10(D, BOOST_PP_AS_STEP_U_D(D,A,10))

# define BOOST_PP_AS_S_12(      A) BOOST_PP_AS_S_11(       BOOST_PP_AS_STEP(      A,11))
# define BOOST_PP_AS_S_U_12(    A) BOOST_PP_AS_S_U_11(     BOOST_PP_AS_STEP_U(    A,11))
# define BOOST_PP_AS_S_D_12(  D,A) BOOST_PP_AS_S_U_11(  D, BOOST_PP_AS_STEP_D(  D,A,11))
# define BOOST_PP_AS_S_U_D_12(D,A) BOOST_PP_AS_S_U_D_11(D, BOOST_PP_AS_STEP_U_D(D,A,11))

# define BOOST_PP_AS_S_13(      A) BOOST_PP_AS_S_12(       BOOST_PP_AS_STEP(      A,12))
# define BOOST_PP_AS_S_U_13(    A) BOOST_PP_AS_S_U_12(     BOOST_PP_AS_STEP_U(    A,12))
# define BOOST_PP_AS_S_D_13(  D,A) BOOST_PP_AS_S_U_12(  D, BOOST_PP_AS_STEP_D(  D,A,12))
# define BOOST_PP_AS_S_U_D_13(D,A) BOOST_PP_AS_S_U_D_12(D, BOOST_PP_AS_STEP_U_D(D,A,12))

# define BOOST_PP_AS_S_14(      A) BOOST_PP_AS_S_13(       BOOST_PP_AS_STEP(      A,13))
# define BOOST_PP_AS_S_U_14(    A) BOOST_PP_AS_S_U_13(     BOOST_PP_AS_STEP_U(    A,13))
# define BOOST_PP_AS_S_D_14(  D,A) BOOST_PP_AS_S_U_13(  D, BOOST_PP_AS_STEP_D(  D,A,13))
# define BOOST_PP_AS_S_U_D_14(D,A) BOOST_PP_AS_S_U_D_13(D, BOOST_PP_AS_STEP_U_D(D,A,13))

# define BOOST_PP_AS_S_15(      A) BOOST_PP_AS_S_14(       BOOST_PP_AS_STEP(      A,14))
# define BOOST_PP_AS_S_U_15(    A) BOOST_PP_AS_S_U_14(     BOOST_PP_AS_STEP_U(    A,14))
# define BOOST_PP_AS_S_D_15(  D,A) BOOST_PP_AS_S_U_14(  D, BOOST_PP_AS_STEP_D(  D,A,14))
# define BOOST_PP_AS_S_U_D_15(D,A) BOOST_PP_AS_S_U_D_14(D, BOOST_PP_AS_STEP_U_D(D,A,14))

# define BOOST_PP_AS_S_16(      A) BOOST_PP_AS_S_15(       BOOST_PP_AS_STEP(      A,15))
# define BOOST_PP_AS_S_U_16(    A) BOOST_PP_AS_S_U_15(     BOOST_PP_AS_STEP_U(    A,15))
# define BOOST_PP_AS_S_D_16(  D,A) BOOST_PP_AS_S_U_15(  D, BOOST_PP_AS_STEP_D(  D,A,15))
# define BOOST_PP_AS_S_U_D_16(D,A) BOOST_PP_AS_S_U_D_15(D, BOOST_PP_AS_STEP_U_D(D,A,15))

# define BOOST_PP_AS_S_17(      A) BOOST_PP_AS_S_16(       BOOST_PP_AS_STEP(      A,16))
# define BOOST_PP_AS_S_U_17(    A) BOOST_PP_AS_S_U_16(     BOOST_PP_AS_STEP_U(    A,16))
# define BOOST_PP_AS_S_D_17(  D,A) BOOST_PP_AS_S_U_16(  D, BOOST_PP_AS_STEP_D(  D,A,16))
# define BOOST_PP_AS_S_U_D_17(D,A) BOOST_PP_AS_S_U_D_16(D, BOOST_PP_AS_STEP_U_D(D,A,16))

# define BOOST_PP_AS_S_18(      A) BOOST_PP_AS_S_17(       BOOST_PP_AS_STEP(      A,17))
# define BOOST_PP_AS_S_U_18(    A) BOOST_PP_AS_S_U_17(     BOOST_PP_AS_STEP_U(    A,17))
# define BOOST_PP_AS_S_D_18(  D,A) BOOST_PP_AS_S_U_17(  D, BOOST_PP_AS_STEP_D(  D,A,17))
# define BOOST_PP_AS_S_U_D_18(D,A) BOOST_PP_AS_S_U_D_17(D, BOOST_PP_AS_STEP_U_D(D,A,17))

# define BOOST_PP_AS_S_19(      A) BOOST_PP_AS_S_18(       BOOST_PP_AS_STEP(      A,18))
# define BOOST_PP_AS_S_U_19(    A) BOOST_PP_AS_S_U_18(     BOOST_PP_AS_STEP_U(    A,18))
# define BOOST_PP_AS_S_D_19(  D,A) BOOST_PP_AS_S_U_18(  D, BOOST_PP_AS_STEP_D(  D,A,18))
# define BOOST_PP_AS_S_U_D_19(D,A) BOOST_PP_AS_S_U_D_18(D, BOOST_PP_AS_STEP_U_D(D,A,18))

# define BOOST_PP_AS_S_20(      A) BOOST_PP_AS_S_19(       BOOST_PP_AS_STEP(      A,19))
# define BOOST_PP_AS_S_U_20(    A) BOOST_PP_AS_S_U_19(     BOOST_PP_AS_STEP_U(    A,19))
# define BOOST_PP_AS_S_D_20(  D,A) BOOST_PP_AS_S_U_19(  D, BOOST_PP_AS_STEP_D(  D,A,19))
# define BOOST_PP_AS_S_U_D_20(D,A) BOOST_PP_AS_S_U_D_19(D, BOOST_PP_AS_STEP_U_D(D,A,19))

# define BOOST_PP_AS_S_21(      A) BOOST_PP_AS_S_20(       BOOST_PP_AS_STEP(      A,20))
# define BOOST_PP_AS_S_U_21(    A) BOOST_PP_AS_S_U_20(     BOOST_PP_AS_STEP_U(    A,20))
# define BOOST_PP_AS_S_D_21(  D,A) BOOST_PP_AS_S_U_20(  D, BOOST_PP_AS_STEP_D(  D,A,20))
# define BOOST_PP_AS_S_U_D_21(D,A) BOOST_PP_AS_S_U_D_20(D, BOOST_PP_AS_STEP_U_D(D,A,20))

# define BOOST_PP_AS_S_22(      A) BOOST_PP_AS_S_21(       BOOST_PP_AS_STEP(      A,21))
# define BOOST_PP_AS_S_U_22(    A) BOOST_PP_AS_S_U_21(     BOOST_PP_AS_STEP_U(    A,21))
# define BOOST_PP_AS_S_D_22(  D,A) BOOST_PP_AS_S_U_21(  D, BOOST_PP_AS_STEP_D(  D,A,21))
# define BOOST_PP_AS_S_U_D_22(D,A) BOOST_PP_AS_S_U_D_21(D, BOOST_PP_AS_STEP_U_D(D,A,21))

# define BOOST_PP_AS_S_23(      A) BOOST_PP_AS_S_22(       BOOST_PP_AS_STEP(      A,22))
# define BOOST_PP_AS_S_U_23(    A) BOOST_PP_AS_S_U_22(     BOOST_PP_AS_STEP_U(    A,22))
# define BOOST_PP_AS_S_D_23(  D,A) BOOST_PP_AS_S_U_22(  D, BOOST_PP_AS_STEP_D(  D,A,22))
# define BOOST_PP_AS_S_U_D_23(D,A) BOOST_PP_AS_S_U_D_22(D, BOOST_PP_AS_STEP_U_D(D,A,22))

# define BOOST_PP_AS_S_24(      A) BOOST_PP_AS_S_23(       BOOST_PP_AS_STEP(      A,23))
# define BOOST_PP_AS_S_U_24(    A) BOOST_PP_AS_S_U_23(     BOOST_PP_AS_STEP_U(    A,23))
# define BOOST_PP_AS_S_D_24(  D,A) BOOST_PP_AS_S_U_23(  D, BOOST_PP_AS_STEP_D(  D,A,23))
# define BOOST_PP_AS_S_U_D_24(D,A) BOOST_PP_AS_S_U_D_23(D, BOOST_PP_AS_STEP_U_D(D,A,23))

# define BOOST_PP_AS_S_25(      A) BOOST_PP_AS_S_24(       BOOST_PP_AS_STEP(      A,24))
# define BOOST_PP_AS_S_U_25(    A) BOOST_PP_AS_S_U_24(     BOOST_PP_AS_STEP_U(    A,24))
# define BOOST_PP_AS_S_D_25(  D,A) BOOST_PP_AS_S_U_24(  D, BOOST_PP_AS_STEP_D(  D,A,24))
# define BOOST_PP_AS_S_U_D_25(D,A) BOOST_PP_AS_S_U_D_24(D, BOOST_PP_AS_STEP_U_D(D,A,24))

# define BOOST_PP_AS_S_26(      A) BOOST_PP_AS_S_25(       BOOST_PP_AS_STEP(      A,25))
# define BOOST_PP_AS_S_U_26(    A) BOOST_PP_AS_S_U_25(     BOOST_PP_AS_STEP_U(    A,25))
# define BOOST_PP_AS_S_D_26(  D,A) BOOST_PP_AS_S_U_25(  D, BOOST_PP_AS_STEP_D(  D,A,25))
# define BOOST_PP_AS_S_U_D_26(D,A) BOOST_PP_AS_S_U_D_25(D, BOOST_PP_AS_STEP_U_D(D,A,25))

# define BOOST_PP_AS_S_27(      A) BOOST_PP_AS_S_26(       BOOST_PP_AS_STEP(      A,26))
# define BOOST_PP_AS_S_U_27(    A) BOOST_PP_AS_S_U_26(     BOOST_PP_AS_STEP_U(    A,26))
# define BOOST_PP_AS_S_D_27(  D,A) BOOST_PP_AS_S_U_26(  D, BOOST_PP_AS_STEP_D(  D,A,26))
# define BOOST_PP_AS_S_U_D_27(D,A) BOOST_PP_AS_S_U_D_26(D, BOOST_PP_AS_STEP_U_D(D,A,26))

# define BOOST_PP_AS_S_28(      A) BOOST_PP_AS_S_27(       BOOST_PP_AS_STEP(      A,27))
# define BOOST_PP_AS_S_U_28(    A) BOOST_PP_AS_S_U_27(     BOOST_PP_AS_STEP_U(    A,27))
# define BOOST_PP_AS_S_D_28(  D,A) BOOST_PP_AS_S_U_27(  D, BOOST_PP_AS_STEP_D(  D,A,27))
# define BOOST_PP_AS_S_U_D_28(D,A) BOOST_PP_AS_S_U_D_27(D, BOOST_PP_AS_STEP_U_D(D,A,27))

# define BOOST_PP_AS_S_29(      A) BOOST_PP_AS_S_28(       BOOST_PP_AS_STEP(      A,28))
# define BOOST_PP_AS_S_U_29(    A) BOOST_PP_AS_S_U_28(     BOOST_PP_AS_STEP_U(    A,28))
# define BOOST_PP_AS_S_D_29(  D,A) BOOST_PP_AS_S_U_28(  D, BOOST_PP_AS_STEP_D(  D,A,28))
# define BOOST_PP_AS_S_U_D_29(D,A) BOOST_PP_AS_S_U_D_28(D, BOOST_PP_AS_STEP_U_D(D,A,28))

# define BOOST_PP_AS_S_30(      A) BOOST_PP_AS_S_29(       BOOST_PP_AS_STEP(      A,29))
# define BOOST_PP_AS_S_U_30(    A) BOOST_PP_AS_S_U_29(     BOOST_PP_AS_STEP_U(    A,29))
# define BOOST_PP_AS_S_D_30(  D,A) BOOST_PP_AS_S_U_29(  D, BOOST_PP_AS_STEP_D(  D,A,29))
# define BOOST_PP_AS_S_U_D_30(D,A) BOOST_PP_AS_S_U_D_29(D, BOOST_PP_AS_STEP_U_D(D,A,29))

# define BOOST_PP_AS_S_31(      A) BOOST_PP_AS_S_30(       BOOST_PP_AS_STEP(      A,30))
# define BOOST_PP_AS_S_U_31(    A) BOOST_PP_AS_S_U_30(     BOOST_PP_AS_STEP_U(    A,30))
# define BOOST_PP_AS_S_D_31(  D,A) BOOST_PP_AS_S_U_30(  D, BOOST_PP_AS_STEP_D(  D,A,30))
# define BOOST_PP_AS_S_U_D_31(D,A) BOOST_PP_AS_S_U_D_30(D, BOOST_PP_AS_STEP_U_D(D,A,30))

# define BOOST_PP_AS_S_32(      A) BOOST_PP_AS_S_31(       BOOST_PP_AS_STEP(      A,31))
# define BOOST_PP_AS_S_U_32(    A) BOOST_PP_AS_S_U_31(     BOOST_PP_AS_STEP_U(    A,31))
# define BOOST_PP_AS_S_D_32(  D,A) BOOST_PP_AS_S_U_31(  D, BOOST_PP_AS_STEP_D(  D,A,31))
# define BOOST_PP_AS_S_U_D_32(D,A) BOOST_PP_AS_S_U_D_31(D, BOOST_PP_AS_STEP_U_D(D,A,31))

# define BOOST_PP_AS_S_33(      A) BOOST_PP_AS_S_32(       BOOST_PP_AS_STEP(      A,32))
# define BOOST_PP_AS_S_U_33(    A) BOOST_PP_AS_S_U_32(     BOOST_PP_AS_STEP_U(    A,32))
# define BOOST_PP_AS_S_D_33(  D,A) BOOST_PP_AS_S_U_32(  D, BOOST_PP_AS_STEP_D(  D,A,32))
# define BOOST_PP_AS_S_U_D_33(D,A) BOOST_PP_AS_S_U_D_32(D, BOOST_PP_AS_STEP_U_D(D,A,32))

# define BOOST_PP_AS_S_34(      A) BOOST_PP_AS_S_33(       BOOST_PP_AS_STEP(      A,33))
# define BOOST_PP_AS_S_U_34(    A) BOOST_PP_AS_S_U_33(     BOOST_PP_AS_STEP_U(    A,33))
# define BOOST_PP_AS_S_D_34(  D,A) BOOST_PP_AS_S_U_33(  D, BOOST_PP_AS_STEP_D(  D,A,33))
# define BOOST_PP_AS_S_U_D_34(D,A) BOOST_PP_AS_S_U_D_33(D, BOOST_PP_AS_STEP_U_D(D,A,33))

# define BOOST_PP_AS_S_35(      A) BOOST_PP_AS_S_34(       BOOST_PP_AS_STEP(      A,34))
# define BOOST_PP_AS_S_U_35(    A) BOOST_PP_AS_S_U_34(     BOOST_PP_AS_STEP_U(    A,34))
# define BOOST_PP_AS_S_D_35(  D,A) BOOST_PP_AS_S_U_34(  D, BOOST_PP_AS_STEP_D(  D,A,34))
# define BOOST_PP_AS_S_U_D_35(D,A) BOOST_PP_AS_S_U_D_34(D, BOOST_PP_AS_STEP_U_D(D,A,34))

# define BOOST_PP_AS_S_36(      A) BOOST_PP_AS_S_35(       BOOST_PP_AS_STEP(      A,35))
# define BOOST_PP_AS_S_U_36(    A) BOOST_PP_AS_S_U_35(     BOOST_PP_AS_STEP_U(    A,35))
# define BOOST_PP_AS_S_D_36(  D,A) BOOST_PP_AS_S_U_35(  D, BOOST_PP_AS_STEP_D(  D,A,35))
# define BOOST_PP_AS_S_U_D_36(D,A) BOOST_PP_AS_S_U_D_35(D, BOOST_PP_AS_STEP_U_D(D,A,35))

# define BOOST_PP_AS_S_37(      A) BOOST_PP_AS_S_36(       BOOST_PP_AS_STEP(      A,36))
# define BOOST_PP_AS_S_U_37(    A) BOOST_PP_AS_S_U_36(     BOOST_PP_AS_STEP_U(    A,36))
# define BOOST_PP_AS_S_D_37(  D,A) BOOST_PP_AS_S_U_36(  D, BOOST_PP_AS_STEP_D(  D,A,36))
# define BOOST_PP_AS_S_U_D_37(D,A) BOOST_PP_AS_S_U_D_36(D, BOOST_PP_AS_STEP_U_D(D,A,36))

# define BOOST_PP_AS_S_38(      A) BOOST_PP_AS_S_37(       BOOST_PP_AS_STEP(      A,37))
# define BOOST_PP_AS_S_U_38(    A) BOOST_PP_AS_S_U_37(     BOOST_PP_AS_STEP_U(    A,37))
# define BOOST_PP_AS_S_D_38(  D,A) BOOST_PP_AS_S_U_37(  D, BOOST_PP_AS_STEP_D(  D,A,37))
# define BOOST_PP_AS_S_U_D_38(D,A) BOOST_PP_AS_S_U_D_37(D, BOOST_PP_AS_STEP_U_D(D,A,37))

# define BOOST_PP_AS_S_39(      A) BOOST_PP_AS_S_38(       BOOST_PP_AS_STEP(      A,38))
# define BOOST_PP_AS_S_U_39(    A) BOOST_PP_AS_S_U_38(     BOOST_PP_AS_STEP_U(    A,38))
# define BOOST_PP_AS_S_D_39(  D,A) BOOST_PP_AS_S_U_38(  D, BOOST_PP_AS_STEP_D(  D,A,38))
# define BOOST_PP_AS_S_U_D_39(D,A) BOOST_PP_AS_S_U_D_38(D, BOOST_PP_AS_STEP_U_D(D,A,38))

# define BOOST_PP_AS_S_40(      A) BOOST_PP_AS_S_39(       BOOST_PP_AS_STEP(      A,39))
# define BOOST_PP_AS_S_U_40(    A) BOOST_PP_AS_S_U_39(     BOOST_PP_AS_STEP_U(    A,39))
# define BOOST_PP_AS_S_D_40(  D,A) BOOST_PP_AS_S_U_39(  D, BOOST_PP_AS_STEP_D(  D,A,39))
# define BOOST_PP_AS_S_U_D_40(D,A) BOOST_PP_AS_S_U_D_39(D, BOOST_PP_AS_STEP_U_D(D,A,39))

# define BOOST_PP_AS_S_41(      A) BOOST_PP_AS_S_40(       BOOST_PP_AS_STEP(      A,40))
# define BOOST_PP_AS_S_U_41(    A) BOOST_PP_AS_S_U_40(     BOOST_PP_AS_STEP_U(    A,40))
# define BOOST_PP_AS_S_D_41(  D,A) BOOST_PP_AS_S_U_40(  D, BOOST_PP_AS_STEP_D(  D,A,40))
# define BOOST_PP_AS_S_U_D_41(D,A) BOOST_PP_AS_S_U_D_40(D, BOOST_PP_AS_STEP_U_D(D,A,40))

# define BOOST_PP_AS_S_42(      A) BOOST_PP_AS_S_41(       BOOST_PP_AS_STEP(      A,41))
# define BOOST_PP_AS_S_U_42(    A) BOOST_PP_AS_S_U_41(     BOOST_PP_AS_STEP_U(    A,41))
# define BOOST_PP_AS_S_D_42(  D,A) BOOST_PP_AS_S_U_41(  D, BOOST_PP_AS_STEP_D(  D,A,41))
# define BOOST_PP_AS_S_U_D_42(D,A) BOOST_PP_AS_S_U_D_41(D, BOOST_PP_AS_STEP_U_D(D,A,41))

# define BOOST_PP_AS_S_43(      A) BOOST_PP_AS_S_42(       BOOST_PP_AS_STEP(      A,42))
# define BOOST_PP_AS_S_U_43(    A) BOOST_PP_AS_S_U_42(     BOOST_PP_AS_STEP_U(    A,42))
# define BOOST_PP_AS_S_D_43(  D,A) BOOST_PP_AS_S_U_42(  D, BOOST_PP_AS_STEP_D(  D,A,42))
# define BOOST_PP_AS_S_U_D_43(D,A) BOOST_PP_AS_S_U_D_42(D, BOOST_PP_AS_STEP_U_D(D,A,42))

# define BOOST_PP_AS_S_44(      A) BOOST_PP_AS_S_43(       BOOST_PP_AS_STEP(      A,43))
# define BOOST_PP_AS_S_U_44(    A) BOOST_PP_AS_S_U_43(     BOOST_PP_AS_STEP_U(    A,43))
# define BOOST_PP_AS_S_D_44(  D,A) BOOST_PP_AS_S_U_43(  D, BOOST_PP_AS_STEP_D(  D,A,43))
# define BOOST_PP_AS_S_U_D_44(D,A) BOOST_PP_AS_S_U_D_43(D, BOOST_PP_AS_STEP_U_D(D,A,43))

# define BOOST_PP_AS_S_45(      A) BOOST_PP_AS_S_44(       BOOST_PP_AS_STEP(      A,44))
# define BOOST_PP_AS_S_U_45(    A) BOOST_PP_AS_S_U_44(     BOOST_PP_AS_STEP_U(    A,44))
# define BOOST_PP_AS_S_D_45(  D,A) BOOST_PP_AS_S_U_44(  D, BOOST_PP_AS_STEP_D(  D,A,44))
# define BOOST_PP_AS_S_U_D_45(D,A) BOOST_PP_AS_S_U_D_44(D, BOOST_PP_AS_STEP_U_D(D,A,44))

# define BOOST_PP_AS_S_46(      A) BOOST_PP_AS_S_45(       BOOST_PP_AS_STEP(      A,45))
# define BOOST_PP_AS_S_U_46(    A) BOOST_PP_AS_S_U_45(     BOOST_PP_AS_STEP_U(    A,45))
# define BOOST_PP_AS_S_D_46(  D,A) BOOST_PP_AS_S_U_45(  D, BOOST_PP_AS_STEP_D(  D,A,45))
# define BOOST_PP_AS_S_U_D_46(D,A) BOOST_PP_AS_S_U_D_45(D, BOOST_PP_AS_STEP_U_D(D,A,45))

# define BOOST_PP_AS_S_47(      A) BOOST_PP_AS_S_46(       BOOST_PP_AS_STEP(      A,46))
# define BOOST_PP_AS_S_U_47(    A) BOOST_PP_AS_S_U_46(     BOOST_PP_AS_STEP_U(    A,46))
# define BOOST_PP_AS_S_D_47(  D,A) BOOST_PP_AS_S_U_46(  D, BOOST_PP_AS_STEP_D(  D,A,46))
# define BOOST_PP_AS_S_U_D_47(D,A) BOOST_PP_AS_S_U_D_46(D, BOOST_PP_AS_STEP_U_D(D,A,46))

# define BOOST_PP_AS_S_48(      A) BOOST_PP_AS_S_47(       BOOST_PP_AS_STEP(      A,47))
# define BOOST_PP_AS_S_U_48(    A) BOOST_PP_AS_S_U_47(     BOOST_PP_AS_STEP_U(    A,47))
# define BOOST_PP_AS_S_D_48(  D,A) BOOST_PP_AS_S_U_47(  D, BOOST_PP_AS_STEP_D(  D,A,47))
# define BOOST_PP_AS_S_U_D_48(D,A) BOOST_PP_AS_S_U_D_47(D, BOOST_PP_AS_STEP_U_D(D,A,47))

# define BOOST_PP_AS_S_49(      A) BOOST_PP_AS_S_48(       BOOST_PP_AS_STEP(      A,48))
# define BOOST_PP_AS_S_U_49(    A) BOOST_PP_AS_S_U_48(     BOOST_PP_AS_STEP_U(    A,48))
# define BOOST_PP_AS_S_D_49(  D,A) BOOST_PP_AS_S_U_48(  D, BOOST_PP_AS_STEP_D(  D,A,48))
# define BOOST_PP_AS_S_U_D_49(D,A) BOOST_PP_AS_S_U_D_48(D, BOOST_PP_AS_STEP_U_D(D,A,48))

# define BOOST_PP_AS_S_50(      A) BOOST_PP_AS_S_49(       BOOST_PP_AS_STEP(      A,49))
# define BOOST_PP_AS_S_U_50(    A) BOOST_PP_AS_S_U_49(     BOOST_PP_AS_STEP_U(    A,49))
# define BOOST_PP_AS_S_D_50(  D,A) BOOST_PP_AS_S_U_49(  D, BOOST_PP_AS_STEP_D(  D,A,49))
# define BOOST_PP_AS_S_U_D_50(D,A) BOOST_PP_AS_S_U_D_49(D, BOOST_PP_AS_STEP_U_D(D,A,49))

# define BOOST_PP_AS_S_51(      A) BOOST_PP_AS_S_50(       BOOST_PP_AS_STEP(      A,50))
# define BOOST_PP_AS_S_U_51(    A) BOOST_PP_AS_S_U_50(     BOOST_PP_AS_STEP_U(    A,50))
# define BOOST_PP_AS_S_D_51(  D,A) BOOST_PP_AS_S_U_50(  D, BOOST_PP_AS_STEP_D(  D,A,50))
# define BOOST_PP_AS_S_U_D_51(D,A) BOOST_PP_AS_S_U_D_50(D, BOOST_PP_AS_STEP_U_D(D,A,50))

# define BOOST_PP_AS_S_52(      A) BOOST_PP_AS_S_51(       BOOST_PP_AS_STEP(      A,51))
# define BOOST_PP_AS_S_U_52(    A) BOOST_PP_AS_S_U_51(     BOOST_PP_AS_STEP_U(    A,51))
# define BOOST_PP_AS_S_D_52(  D,A) BOOST_PP_AS_S_U_51(  D, BOOST_PP_AS_STEP_D(  D,A,51))
# define BOOST_PP_AS_S_U_D_52(D,A) BOOST_PP_AS_S_U_D_51(D, BOOST_PP_AS_STEP_U_D(D,A,51))

# define BOOST_PP_AS_S_53(      A) BOOST_PP_AS_S_52(       BOOST_PP_AS_STEP(      A,52))
# define BOOST_PP_AS_S_U_53(    A) BOOST_PP_AS_S_U_52(     BOOST_PP_AS_STEP_U(    A,52))
# define BOOST_PP_AS_S_D_53(  D,A) BOOST_PP_AS_S_U_52(  D, BOOST_PP_AS_STEP_D(  D,A,52))
# define BOOST_PP_AS_S_U_D_53(D,A) BOOST_PP_AS_S_U_D_52(D, BOOST_PP_AS_STEP_U_D(D,A,52))

# define BOOST_PP_AS_S_54(      A) BOOST_PP_AS_S_53(       BOOST_PP_AS_STEP(      A,53))
# define BOOST_PP_AS_S_U_54(    A) BOOST_PP_AS_S_U_53(     BOOST_PP_AS_STEP_U(    A,53))
# define BOOST_PP_AS_S_D_54(  D,A) BOOST_PP_AS_S_U_53(  D, BOOST_PP_AS_STEP_D(  D,A,53))
# define BOOST_PP_AS_S_U_D_54(D,A) BOOST_PP_AS_S_U_D_53(D, BOOST_PP_AS_STEP_U_D(D,A,53))

# define BOOST_PP_AS_S_55(      A) BOOST_PP_AS_S_54(       BOOST_PP_AS_STEP(      A,54))
# define BOOST_PP_AS_S_U_55(    A) BOOST_PP_AS_S_U_54(     BOOST_PP_AS_STEP_U(    A,54))
# define BOOST_PP_AS_S_D_55(  D,A) BOOST_PP_AS_S_U_54(  D, BOOST_PP_AS_STEP_D(  D,A,54))
# define BOOST_PP_AS_S_U_D_55(D,A) BOOST_PP_AS_S_U_D_54(D, BOOST_PP_AS_STEP_U_D(D,A,54))

# define BOOST_PP_AS_S_56(      A) BOOST_PP_AS_S_55(       BOOST_PP_AS_STEP(      A,55))
# define BOOST_PP_AS_S_U_56(    A) BOOST_PP_AS_S_U_55(     BOOST_PP_AS_STEP_U(    A,55))
# define BOOST_PP_AS_S_D_56(  D,A) BOOST_PP_AS_S_U_55(  D, BOOST_PP_AS_STEP_D(  D,A,55))
# define BOOST_PP_AS_S_U_D_56(D,A) BOOST_PP_AS_S_U_D_55(D, BOOST_PP_AS_STEP_U_D(D,A,55))

# define BOOST_PP_AS_S_57(      A) BOOST_PP_AS_S_56(       BOOST_PP_AS_STEP(      A,56))
# define BOOST_PP_AS_S_U_57(    A) BOOST_PP_AS_S_U_56(     BOOST_PP_AS_STEP_U(    A,56))
# define BOOST_PP_AS_S_D_57(  D,A) BOOST_PP_AS_S_U_56(  D, BOOST_PP_AS_STEP_D(  D,A,56))
# define BOOST_PP_AS_S_U_D_57(D,A) BOOST_PP_AS_S_U_D_56(D, BOOST_PP_AS_STEP_U_D(D,A,56))

# define BOOST_PP_AS_S_58(      A) BOOST_PP_AS_S_57(       BOOST_PP_AS_STEP(      A,57))
# define BOOST_PP_AS_S_U_58(    A) BOOST_PP_AS_S_U_57(     BOOST_PP_AS_STEP_U(    A,57))
# define BOOST_PP_AS_S_D_58(  D,A) BOOST_PP_AS_S_U_57(  D, BOOST_PP_AS_STEP_D(  D,A,57))
# define BOOST_PP_AS_S_U_D_58(D,A) BOOST_PP_AS_S_U_D_57(D, BOOST_PP_AS_STEP_U_D(D,A,57))

# define BOOST_PP_AS_S_59(      A) BOOST_PP_AS_S_58(       BOOST_PP_AS_STEP(      A,58))
# define BOOST_PP_AS_S_U_59(    A) BOOST_PP_AS_S_U_58(     BOOST_PP_AS_STEP_U(    A,58))
# define BOOST_PP_AS_S_D_59(  D,A) BOOST_PP_AS_S_U_58(  D, BOOST_PP_AS_STEP_D(  D,A,58))
# define BOOST_PP_AS_S_U_D_59(D,A) BOOST_PP_AS_S_U_D_58(D, BOOST_PP_AS_STEP_U_D(D,A,58))

# define BOOST_PP_AS_S_60(      A) BOOST_PP_AS_S_59(       BOOST_PP_AS_STEP(      A,59))
# define BOOST_PP_AS_S_U_60(    A) BOOST_PP_AS_S_U_59(     BOOST_PP_AS_STEP_U(    A,59))
# define BOOST_PP_AS_S_D_60(  D,A) BOOST_PP_AS_S_U_59(  D, BOOST_PP_AS_STEP_D(  D,A,59))
# define BOOST_PP_AS_S_U_D_60(D,A) BOOST_PP_AS_S_U_D_59(D, BOOST_PP_AS_STEP_U_D(D,A,59))

# define BOOST_PP_AS_S_61(      A) BOOST_PP_AS_S_60(       BOOST_PP_AS_STEP(      A,60))
# define BOOST_PP_AS_S_U_61(    A) BOOST_PP_AS_S_U_60(     BOOST_PP_AS_STEP_U(    A,60))
# define BOOST_PP_AS_S_D_61(  D,A) BOOST_PP_AS_S_U_60(  D, BOOST_PP_AS_STEP_D(  D,A,60))
# define BOOST_PP_AS_S_U_D_61(D,A) BOOST_PP_AS_S_U_D_60(D, BOOST_PP_AS_STEP_U_D(D,A,60))

# define BOOST_PP_AS_S_62(      A) BOOST_PP_AS_S_61(       BOOST_PP_AS_STEP(      A,61))
# define BOOST_PP_AS_S_U_62(    A) BOOST_PP_AS_S_U_61(     BOOST_PP_AS_STEP_U(    A,61))
# define BOOST_PP_AS_S_D_62(  D,A) BOOST_PP_AS_S_U_61(  D, BOOST_PP_AS_STEP_D(  D,A,61))
# define BOOST_PP_AS_S_U_D_62(D,A) BOOST_PP_AS_S_U_D_61(D, BOOST_PP_AS_STEP_U_D(D,A,61))

# define BOOST_PP_AS_S_63(      A) BOOST_PP_AS_S_62(       BOOST_PP_AS_STEP(      A,62))
# define BOOST_PP_AS_S_U_63(    A) BOOST_PP_AS_S_U_62(     BOOST_PP_AS_STEP_U(    A,62))
# define BOOST_PP_AS_S_D_63(  D,A) BOOST_PP_AS_S_U_62(  D, BOOST_PP_AS_STEP_D(  D,A,62))
# define BOOST_PP_AS_S_U_D_63(D,A) BOOST_PP_AS_S_U_D_62(D, BOOST_PP_AS_STEP_U_D(D,A,62))

# define BOOST_PP_AS_S_64(      A) BOOST_PP_AS_S_63(       BOOST_PP_AS_STEP(      A,63))
# define BOOST_PP_AS_S_U_64(    A) BOOST_PP_AS_S_U_63(     BOOST_PP_AS_STEP_U(    A,63))
# define BOOST_PP_AS_S_D_64(  D,A) BOOST_PP_AS_S_U_63(  D, BOOST_PP_AS_STEP_D(  D,A,63))
# define BOOST_PP_AS_S_U_D_64(D,A) BOOST_PP_AS_S_U_D_63(D, BOOST_PP_AS_STEP_U_D(D,A,63))


// /*
// ** BOOST_PP_ARRAY_SORT
// ** Sorts the given PP_ARRAY.
// ** _U variants remove duplicates.
// ** _D variants use the next available PP_WHILE iteration
// */
//
// # define BOOST_PP_ARRAY_SORT(A)        BOOST_PP_AS_RES(BOOST_PP_WHILE(                  BOOST_PP_AS_PRED, BOOST_PP_AS_OP,   (A, 0, (0, ()))))
// # define BOOST_PP_ARRAY_SORT_U(A)      BOOST_PP_AS_RES(BOOST_PP_WHILE(                  BOOST_PP_AS_PRED, BOOST_PP_AS_OP_U, (A, 0, (0, ()))))
// # define BOOST_PP_ARRAY_SORT_D(D, A)   BOOST_PP_AS_RES(BOOST_PP_CAT(BOOST_PP_WHILE_, D)(BOOST_PP_AS_PRED, BOOST_PP_AS_OP,   (A, 0, (0, ()))))
// # define BOOST_PP_ARRAY_SORT_U_D(D, A) BOOST_PP_AS_RES(BOOST_PP_CAT(BOOST_PP_WHILE_, D)(BOOST_PP_AS_PRED, BOOST_PP_AS_OP_U, (A, 0, (0, ()))))
//
//
//
// /*
// ** Internal helpers
// */
//
// # define BOOST_PP_AS_LB(D, S) BOOST_PP_ARRAY_LOWER_BOUND_D(D, BOOST_PP_AS_RES(S), BOOST_PP_AS_ARRAY_ELEM(S))
//
// # define BOOST_PP_AS_ARRAY_ELEM(S)  BOOST_PP_ARRAY_ELEM(BOOST_PP_AS_INDEX(S), BOOST_PP_AS_ARRAY(S))
// # define BOOST_PP_AS_ARRAY_SIZE(S)  BOOST_PP_ARRAY_SIZE(BOOST_PP_AS_ARRAY(S))
// # define BOOST_PP_AS_ARRAY(S)       BOOST_PP_TUPLE_ELEM(3, 0, S)
// # define BOOST_PP_AS_INDEX(S)       BOOST_PP_TUPLE_ELEM(3, 1, S)
// # define BOOST_PP_AS_RES(S)         BOOST_PP_TUPLE_ELEM(3, 2, S)
//
// # define BOOST_PP_AS_MERGE(  D, E, R, P) BOOST_PP_ARRAY_INSERT_D(D, R, P, E)
// # define BOOST_PP_AS_MERGE_R(D, E, R, P) BOOST_PP_IF(BOOST_PP_LESS(E, BOOST_PP_ARRAY_ELEM(P, R)), BOOST_PP_AS_MERGE(D, E, R, P), R)
// # define BOOST_PP_AS_MERGE_U(D, E, R, P) BOOST_PP_IF(BOOST_PP_LESS(P, BOOST_PP_ARRAY_SIZE(R)), BOOST_PP_AS_MERGE_R, BOOST_PP_AS_MERGE)(D, E, R, P)
//
// # define BOOST_PP_AS_PRED(D, S) BOOST_PP_LESS_D(D, BOOST_PP_AS_INDEX(S), BOOST_PP_AS_ARRAY_SIZE(S))
// # define BOOST_PP_AS_OP(  D, S) (BOOST_PP_AS_ARRAY(S), BOOST_PP_INC(BOOST_PP_AS_INDEX(S)), BOOST_PP_AS_MERGE  (D, BOOST_PP_AS_ARRAY_ELEM(S), BOOST_PP_AS_RES(S), BOOST_PP_AS_LB(D, S)))
// # define BOOST_PP_AS_OP_U(D, S) (BOOST_PP_AS_ARRAY(S), BOOST_PP_INC(BOOST_PP_AS_INDEX(S)), BOOST_PP_AS_MERGE_U(D, BOOST_PP_AS_ARRAY_ELEM(S), BOOST_PP_AS_RES(S), BOOST_PP_AS_LB(D, S)))



#endif /* !BOOST_PREPROCESSOR_ARRAY_SORT_HPP */

